title: "Enzo Kouokam — Data Scientist"
logo: img/picture.jpg
description: "Portfolio Data Science & Business Intelligence | Machine Learning · Python · SQL · Power BI"
show_downloads: true
theme: jekyll-theme-minimal
lang: fr
